trigger:
- none

pool: 
  name: TC_811

variables:
  dcusername: 'dcadmin'
  dcpassword: 'dcadmin'
  DC_QUICK_DEPLOY_PATH: '/opt/app/siemens/dc_14.1/deployment_center/additional_tools/internal/dc_quick_deploy'
  DC_URL: 'http://192.168.80.54:8080/deploymentcenter'
  DC_DEPLOY_SCRIPT_DIR_NAME: 'deploy'
  JAVA_HOME: '/opt/app/siemens/JAVA/jdk-11.0.21'
  TARGET_VM_DEPLOY_SCRIPTS_DIR: '/opt/app/siemens/'
  TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO: '/opt/app/siemens/dc_14.1/repository/deploy_scripts'
  TARGET_VM_SOFTWARE_LOCATION: '/opt/app/siemens/dc_14.1/repository/software'  # SoftwareLocation

stages:
- stage: Prepare
  jobs:
  - job: Prepare_Azure_Variables
    pool:
      name: TC_811
    steps:
    - script: |
        # Setting the specified variables
        
        target_vm_machine_name='DENBG0817VM'
        dcEnvironmentName=test01
        machine_script_dir_name='deploy_'$target_vm_machine_name
        machine_script_zip_name=$machine_script_dir_name.zip
        scripts_dir_name='$(DC_DEPLOY_SCRIPT_DIR_NAME)_$(Build.BuildNumber)'
        machine_script_path=$(TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO)/$dcEnvironmentName/install/$scripts_dir_name/$machine_script_zip_name
        unzip_target_path=$(TARGET_VM_DEPLOY_SCRIPTS_DIR)/$scripts_dir_name/$machine_script_dir_name
        echo "$target_vm_machine_name"
        echo "$machine_script_dir_name"
        echo "$machine_script_zip_name"
        echo "$scripts_dir_name"
        echo "$machine_script_path"
        echo "$unzip_target_path"
        echo "$(Build.BuildNumber)"
      displayName: 'Prepare Azure Variables'

- stage: Generate_Deploy_Script
  jobs:
  - job: Generate
    pool:
      name: TC_811
    steps:
    - script: |
        TARGET_VM_MACHINE_NAME=DENBG0817VM
        DC_ENV_NAME=test01
        INPUT_FILE_PATH='/opt/app/siemens/Sample_xml_Files/test_install_Fnd140.xml'
        SCRIPTS_DIR_NAME='$(DC_DEPLOY_SCRIPT_DIR_NAME)_$(Build.BuildNumber)'
        echo "Generating Deploy script using Quick Deploy"
        cd $(DC_QUICK_DEPLOY_PATH)
        ./dc_quick_deploy.sh -dcurl=$(DC_URL) -environment=$DC_ENV_NAME -inputFile=$INPUT_FILE_PATH -dcusername=$(dcusername) -dcpassword=$(dcpassword) -machine=$TARGET_VM_MACHINE_NAME
      displayName: 'Generate Deploy Script'

- stage: Copy_Deploy_Script
  jobs:
  - job: Copy
    pool:
      name: TC_811
    steps:
    - script: |
        echo "Copying files to the destination server"
        scp -r $(TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO)/$(DC_ENV_NAME)/install/$(SCRIPTS_DIR_NAME)/$(machine_script_zip_name) infodba@192.168.80.108:$(TARGET_VM_DEPLOY_SCRIPTS_DIR)
      displayName: 'Copy Files to Destination Server'

- stage: Unzip_Deploy_Script
  jobs:
  - job: Unzip
    pool:
      name: TC_811
    steps:
    - script: |
        echo "Unzipping files to the destination server"
        ssh -T -o StrictHostKeyChecking=no infodba@192.168.80.108 unzip $(TARGET_VM_DEPLOY_SCRIPTS_DIR)/$(SCRIPTS_DIR_NAME)/$(MACHINE_SCRIPT_ZIP_NAME) -d $(TARGET_VM_DEPLOY_SCRIPTS_DIR)/$(SCRIPTS_DIR_NAME)
      displayName: 'Unzip Files on Destination Server'
